const { PrismaClient } = require("@prisma/client")
const prisma = new PrismaClient()

async function main() {
  const influencers = [
    {
      name: "Priya Sharma",
      handle: "@priyaeats",
      location: "Mumbai",
      niche: "Food",
      platform: "Instagram",
      followers: "84K",
      engagement: "6.2%",
      score: 91,
      rate: "₹8,000",
      initials: "PS",
      about: "Food blogger and recipe creator based in Mumbai. Specialises in Indian home cooking and restaurant reviews.",
      email: "priya@priyaeats.com",
      phone: "+91 98765 00001",
      verified: true,
    },
    {
      name: "Rohit Kumar",
      handle: "@rohittech",
      location: "Bangalore",
      niche: "Tech",
      platform: "YouTube",
      followers: "210K",
      engagement: "4.8%",
      score: 87,
      rate: "₹25,000",
      initials: "RK",
      about: "Tech reviewer and gadget enthusiast. Covers smartphones, laptops, and emerging tech for Indian consumers.",
      email: "rohit@rohittech.in",
      phone: "+91 98765 00002",
      verified: true,
    },
    {
      name: "Ananya Nair",
      handle: "@ananyafits",
      location: "Delhi",
      niche: "Fitness",
      platform: "Instagram",
      followers: "42K",
      engagement: "8.1%",
      score: 79,
      rate: "₹4,000",
      initials: "AN",
      about: "Certified fitness trainer and nutrition coach. Helps working professionals stay fit with home workouts.",
      email: "ananya@ananyafits.com",
      phone: "+91 98765 00003",
      verified: false,
    },
    {
      name: "Vikram Mehta",
      handle: "@vikramfinance",
      location: "Chennai",
      niche: "Finance",
      platform: "LinkedIn",
      followers: "38K",
      engagement: "5.4%",
      score: 84,
      rate: "₹6,000",
      initials: "VM",
      about: "Personal finance advisor and stock market educator. Makes investing simple for young Indians.",
      email: "vikram@vikramfinance.in",
      phone: "+91 98765 00004",
      verified: true,
    },
    {
      name: "Sneha Patel",
      handle: "@snehastyle",
      location: "Ahmedabad",
      niche: "Fashion",
      platform: "Instagram",
      followers: "95K",
      engagement: "7.3%",
      score: 88,
      rate: "₹12,000",
      initials: "SP",
      about: "Fashion and lifestyle creator specialising in Indian ethnic wear and sustainable fashion.",
      email: "sneha@snehastyle.com",
      phone: "+91 98765 00005",
      verified: true,
    },
    {
      name: "Arjun Das",
      handle: "@arjuntravels",
      location: "Kolkata",
      niche: "Travel",
      platform: "YouTube",
      followers: "156K",
      engagement: "5.9%",
      score: 82,
      rate: "₹18,000",
      initials: "AD",
      about: "Budget travel creator covering hidden gems across India and Southeast Asia.",
      email: "arjun@arjuntravels.com",
      phone: "+91 98765 00006",
      verified: false,
    },
    {
      name: "Meera Iyer",
      handle: "@meeracooks",
      location: "Hyderabad",
      niche: "Food",
      platform: "Instagram",
      followers: "62K",
      engagement: "7.8%",
      score: 86,
      rate: "₹7,500",
      initials: "MI",
      about: "South Indian food specialist sharing authentic recipes and regional cuisine stories.",
      email: "meera@meeracooks.com",
      phone: "+91 98765 00007",
      verified: true,
    },
    {
      name: "Karan Singh",
      handle: "@karangames",
      location: "Pune",
      niche: "Gaming",
      platform: "YouTube",
      followers: "320K",
      engagement: "3.9%",
      score: 80,
      rate: "₹30,000",
      initials: "KS",
      about: "Professional gamer and gaming content creator. Reviews games and streams live tournaments.",
      email: "karan@karangames.in",
      phone: "+91 98765 00008",
      verified: true,
    },
    {
      name: "Divya Rao",
      handle: "@divyabeauty",
      location: "Bangalore",
      niche: "Fashion",
      platform: "Instagram",
      followers: "78K",
      engagement: "6.8%",
      score: 85,
      rate: "₹9,000",
      initials: "DR",
      about: "Beauty and skincare creator focused on Indian skin tones and affordable products.",
      email: "divya@divyabeauty.com",
      phone: "+91 98765 00009",
      verified: false,
    },
  ]

  for (const influencer of influencers) {
    await prisma.influencer.upsert({
      where: { handle: influencer.handle },
      update: influencer,
      create: influencer,
    })
  }

  console.log("Seeded", influencers.length, "influencers")
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())