export const NICHES = [
  "Fashion",
  "Beauty",
  "Tech",
  "Food & Beverage",
  "Health & Fitness",
  "Travel",
  "Lifestyle",
  "Gaming",
  "Entertainment",
  "Education",
  "Finance",
  "Sports",
  "Music",
  "Comedy",
  "Parenting",
  "Pets",
  "Books & Literature",
  "Automotive",
  "Home & Interior",
  "Photography",
  "Art & Design",
  "Spirituality & Wellness",
  "Environment & Sustainability",
  "Business & Entrepreneurship",
  "Relationships & Dating",
  "Other",
]

export const PLATFORMS = [
  "Instagram",
  "YouTube",
  "Twitter/X",
  "LinkedIn",
  "Facebook",
  "Snapchat",
  "Pinterest",
  "Moj",
  "Josh",
  "ShareChat",
  "Telegram",
  "Other",
]

export const CONTENT_TYPES = [
  "Instagram Post",
  "Instagram Reel",
  "Instagram Story",
  "YouTube Video",
  "YouTube Shorts",
  "Twitter/X Thread",
  "LinkedIn Post",
  "Blog Post",
  "Podcast Mention",
  "Multiple Deliverables",
  "Other",
]

export const INDUSTRIES = [
  "Fashion & Apparel",
  "Beauty & Personal Care",
  "Technology",
  "Food & Beverage",
  "Health & Wellness",
  "Travel & Hospitality",
  "Education & E-learning",
  "Finance & Fintech",
  "Entertainment & Media",
  "Gaming",
  "Automotive",
  "Home & Furniture",
  "Sports & Fitness",
  "Retail & E-commerce",
  "Real Estate",
  "FMCG",
  "Pharmaceutical",
  "Non-profit",
  "Other",
]
